FROM node:20.12.0-alpine3.19

# Set working directory
WORKDIR /usr/src/app

# Copy only package-related files first to leverage Docker cache
COPY package.json package-lock.json turbo.json tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma client
RUN npm run db:generate

RUN npm run build:bank-webhook

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "run", "start-user-app"]
